title: Site

tabs:
  main:
    label: Site
    icon: home
    columns:
      content:
        width: 2/3
        sections:
          content:
            type: fields
            fields:
              tagline:
                type: text
                label: Tagline
              about:
                type: textarea
                label: About text
                size: medium
              slideshow:
                type: files
                label: Slideshow photos
      sidebar:
        width: 1/3
        sections:
          meta:
            type: fields
            fields:
              email:
                type: email
                label: Contact email
              logo:
                type: files
                label: Logo
                max: 1
          social:
            type: fields
            label: Social media
            fields:
              social_items:
                type: structure
                label: Social media items
                fields:
                  icon:
                    type: files
                    label: Icon
                    max: 1
                  label:
                    type: text
                    label: Label
                  url:
                    type: url
                    label: URL
                  inblank:
                    type: toggle
                    label: Open in new tab


  pages:
    label: Pages
    icon: page
    sections:
      pages:
        type: pages
        templates:
          - home
          - galleries
          - default

  seo:
    extends: seo